#!/usr/bin/python3
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# OSU ID: <last.#>
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# sampleclient -- Socket Programming ECHO Client
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
import socket
import sys 

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Global Variables
#···············································································

serverIP = '127.0.0.1'              # loopback address (localhost)
serverPort = '8090'                   # non-privileged port > 1024
serverAddress = (serverIP,serverPort)        # Transport layer address = IP + port
processingUserInput = True                   # Flag for processing

#···············································································

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Application Main
#
def main():

	#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	# 
	#
	try:
		clientSocket=socket.socket(socket.AF_INET,<socket type>)
		print('echoTCPclient :: Client socket object created')
		processingUserInput=True

		#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		# 
		#
		try:
			clientSocket.connect(serverAddress)
			print('echoTCPclient :: Connected to SIMPServer ',serverAddress)
			processingUserInput=True
		except:
			print('echoTCPclient :: Unable to connect to server ',serverAddress)
			processingUserInput=False

	except:
		print('echoTCPclient :: Unable to create client socket')
		processingUserInput=False

	#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	# prompt for and receive command strings until close
	#
	while processingUserInput:

		commandString=input('echoTCPclient► ')
		print('echoTCPclient :: String received ',commandString)

		#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		# prepare to stop if close
		#
		if commandString == 'close' or commandString == 'exit' or commandString == 'quit':
			processingUserInput=False

		#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		# send request to SIMP server
		#
		print('echoTCPclient :: Sending client request ',commandString)
		clientSocket.send(commandString.encode())

		#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		# Wait for server response
		#
		serverResponse=clientSocket.recv(2048)
		serverResponse=serverResponse.decode()
		print('echoTCPclient :: Server response received ',serverResponse)

	clientSocket.close()

if __name__ == "__main__":
	sys.exit(main())
